#!/bin/sh -e


check_make_ok() {
  if [ $? != 0 ]; then
    echo ""
    echo "Make Failed..."
    echo "Please check the messages and fix any problems. If you're still stuck,"
    echo "then please email all the output and as many details as you can to"
    echo "  projects@drogon.net"
    echo ""
    exit 1
  fi
}

if [ x$1 = "xclean" ]; then
  cd wiringLMK
  echo -n "wiringLMK:   "	; make clean
  cd ../devLib
  echo -n "DevLib:     "	; make clean
  cd ../gpio
  echo -n "gpio:       "	; make clean
  cd ../examples
  echo -n "Examples:   "	; make clean
  cd Gertboard
  echo -n "Gertboard:  "	; make clean
  cd ../PiFace
  echo -n "PiFace:     "	; make clean
  cd ../q2w
  echo -n "Quick2Wire: "	; make clean
  cd ../PiGlow
  echo -n "PiGlow:     "	; make clean
  exit
fi

if [ x$1 = "xuninstall" ]; then
  cd wiringLMK
  echo -n "wiringLMK: " ; sudo make uninstall
  cd ../devLib
  echo -n "DevLib:   " ; sudo make uninstall
  cd ../gpio
  echo -n "gpio:     " ; sudo make uninstall
  exit
fi

# Only if you know what you're doing!

if [ x$1 = "xdebian" ]; then
  here=`pwd`
  cd debian-template/wiringPi
  rm -rf usr
  cd $here/wiringPi
  make install-deb
  cd $here/devLib
  make install-deb INCLUDE='-I. -I../wiringPi'
  cd $here/gpio
  make install-deb INCLUDE='-I../wiringPi -I../devLib' LDFLAGS=-L../debian-template/wiringPi/usr/lib
  cd $here/debian-template
  fakeroot dpkg-deb --build wiringPi
  mv wiringPi.deb  wiringpi-`cat $here/VERSION`-1.deb
  exit
fi

if [ x$1 != "x" ]; then
  echo "Usage: $0 [clean | uninstall]"
  exit 1
fi

  echo "wiringLMK Build script"
  echo "====================="
  echo

  echo
  echo "WiringLMK Library"
  cd wiringLMK
  sudo make uninstall
  if [ x$1 = "xstatic" ]; then
    make -j4 static
    check_make_ok
    sudo make install-static
  else
    make -j4
    check_make_ok
    sudo make install
  fi
  check_make_ok

  echo
  echo "WiringPi Devices Library"
  cd ../devLib
  sudo make uninstall
  if [ x$1 = "xstatic" ]; then
    make -j4 static
    check_make_ok
    sudo make install-static
  else
    make -j4
    check_make_ok
    sudo make install
  fi
  check_make_ok

  echo
  echo "GPIO Utility"
  cd ../gpio
  make -j4
  check_make_ok
  sudo make install
  check_make_ok

# echo
# echo "Examples"
# cd ../examples
# make
# cd ..

echo
echo All Done.
echo ""
echo "NOTE: To compile programs with wiringLMK, you need to add:"
echo "    -lwiringPi"
echo "  to your compile line(s) To use the Gertboard, MaxDetect, etc."
echo "  code (the devLib), you need to also add:"
echo "    -lwiringPiDev"
echo "  to your compile line(s)."
echo ""
